# configs/app.yaml

app:
  name: "Leilões Sys"
  env: "dev"         # Altere para "staging" ou "prod" conforme necessário
  debug: false
  port: 8080         # Valor inteiro, sem aspas!
  timezone: "America/Sao_Paulo"

logging:
  level: "info"
  format: "json"
  file_path: "/var/log/leiloesys.log"

cache:
  enabled: true
  ttl_minutes: 30